# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1324c76845534c368690d2a8264da2be9939943323e9092989d877246ac142ead9284a9b24cde990cc90412fb427a1fa7eeb51d095dc3f605b292a16ff4dbc30

test:
  secret_key_base: d52c749d59565ed24dfd01f521860639a7a5b1fd98652f0aa45e5916b08c8f7e297d9918ef6f9cedc6335420d85e948303c80a9e4f4decd28b259e0f57c3438a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
